library(dplyr)
library(tidytext)
library(tidyr)
data(stop_words)

setwd('C:/Users/jrado/Desktop/Fake Thumbdrive/zzY3S2/BC3409 AI in Acct & Finance/zzPA/15 Text Analytics')

news1 <- readLines("news1.txt") # ansi txt
news2 <- readLines("news2.txt") # ansi txt
news3 <- readLines("news3.txt") # ansi txt
news4 <- readLines("news4.txt") # ansi txt
news5 <- readLines("news5.txt") # ansi txt
news6 <- readLines("news6.txt") # ansi txt
news7 <- readLines("news7.txt") # ansi txt
news8 <- readLines("news8.txt") # ansi txt
news9 <- readLines("news9.txt") # ansi txt
news10 <- readLines("news10.txt") # ansi txt
news11 <- readLines("news11.txt") # ansi txt
news12 <- readLines("news12.txt") # ansi txt
news13 <- readLines("news13.txt") # ansi txt
news14 <- readLines("news14.txt") # ansi txt
news15 <- readLines("news15.txt") # ansi txt
news16 <- readLines("news16.txt") # ansi txt
news17 <- readLines("news17.txt") # ansi txt
news18 <- readLines("news18.txt") # ansi txt
news19 <- readLines("news19.txt") # ansi txt
news20 <- readLines("news20.txt") # ansi txt
news21 <- readLines("news21.txt") # ansi txt
news22 <- readLines("news22.txt") # ansi txt
news23 <- readLines("news23.txt") # ansi txt
news24 <- readLines("news24.txt") # ansi txt
news25 <- readLines("news25.txt") # ansi txt
news26 <- readLines("news26.txt") # ansi txt
news27 <- readLines("news27.txt") # ansi txt
news28 <- readLines("news28.txt") # ansi txt
news29 <- readLines("news29.txt") # ansi txt
news30 <- readLines("news30.txt") # ansi txt

news1 <- data_frame(text = news1)
news1.t <- news1 %>% unnest_tokens(word, text)
news1.t <- news1.t %>% anti_join(stop_words)

news2 <- data_frame(text = news2)
news2.t <- news2 %>% unnest_tokens(word, text)
news2.t <- news2.t %>% anti_join(stop_words)

news3 <- data_frame(text = news3)
news3.t <- news3 %>% unnest_tokens(word, text)
news3.t <- news3.t %>% anti_join(stop_words)

news4 <- data_frame(text = news4)
news4.t <- news4 %>% unnest_tokens(word, text)
news4.t <- news4.t %>% anti_join(stop_words)

news5 <- data_frame(text = news5)
news5.t <- news5 %>% unnest_tokens(word, text)
news5.t <- news5.t %>% anti_join(stop_words)

news6 <- data_frame(text = news6)
news6.t <- news6 %>% unnest_tokens(word, text)
news6.t <- news6.t %>% anti_join(stop_words)

news7 <- data_frame(text = news7)
news7.t <- news7 %>% unnest_tokens(word, text)
news7.t <- news7.t %>% anti_join(stop_words)

news8 <- data_frame(text = news8)
news8.t <- news8 %>% unnest_tokens(word, text)
news8.t <- news8.t %>% anti_join(stop_words)

news9 <- data_frame(text = news9)
news9.t <- news9 %>% unnest_tokens(word, text)
news9.t <- news9.t %>% anti_join(stop_words)

news10 <- data_frame(text = news10)
news10.t <- news10 %>% unnest_tokens(word, text)
news10.t <- news10.t %>% anti_join(stop_words)

news11 <- data_frame(text = news11)
news11.t <- news11 %>% unnest_tokens(word, text)
news11.t <- news11.t %>% anti_join(stop_words)

news12 <- data_frame(text = news12)
news12.t <- news12 %>% unnest_tokens(word, text)
news12.t <- news12.t %>% anti_join(stop_words)

news13 <- data_frame(text = news13)
news13.t <- news13 %>% unnest_tokens(word, text)
news13.t <- news13.t %>% anti_join(stop_words)

news14 <- data_frame(text = news14)
news14.t <- news14 %>% unnest_tokens(word, text)
news14.t <- news14.t %>% anti_join(stop_words)

news15 <- data_frame(text = news15)
news15.t <- news15 %>% unnest_tokens(word, text)
news15.t <- news15.t %>% anti_join(stop_words)

news16 <- data_frame(text = news16)
news16.t <- news16 %>% unnest_tokens(word, text)
news16.t <- news16.t %>% anti_join(stop_words)

news17 <- data_frame(text = news17)
news17.t <- news17 %>% unnest_tokens(word, text)
news17.t <- news17.t %>% anti_join(stop_words)

news18 <- data_frame(text = news18)
news18.t <- news18 %>% unnest_tokens(word, text)
news18.t <- news18.t %>% anti_join(stop_words)

news19 <- data_frame(text = news19)
news19.t <- news19 %>% unnest_tokens(word, text)
news19.t <- news19.t %>% anti_join(stop_words)

news20 <- data_frame(text = news20)
news20.t <- news20 %>% unnest_tokens(word, text)
news20.t <- news20.t %>% anti_join(stop_words)

news21 <- data_frame(text = news21)
news21.t <- news21 %>% unnest_tokens(word, text)
news21.t <- news21.t %>% anti_join(stop_words)

news22 <- data_frame(text = news22)
news22.t <- news22 %>% unnest_tokens(word, text)
news22.t <- news22.t %>% anti_join(stop_words)

news23 <- data_frame(text = news23)
news23.t <- news23 %>% unnest_tokens(word, text)
news23.t <- news23.t %>% anti_join(stop_words)

news24 <- data_frame(text = news24)
news24.t <- news24 %>% unnest_tokens(word, text)
news24.t <- news24.t %>% anti_join(stop_words)

news25 <- data_frame(text = news25)
news25.t <- news25 %>% unnest_tokens(word, text)
news25.t <- news25.t %>% anti_join(stop_words)

news26 <- data_frame(text = news26)
news26.t <- news26 %>% unnest_tokens(word, text)
news26.t <- news26.t %>% anti_join(stop_words)

news27 <- data_frame(text = news27)
news27.t <- news27 %>% unnest_tokens(word, text)
news27.t <- news27.t %>% anti_join(stop_words)

news28 <- data_frame(text = news28)
news28.t <- news28 %>% unnest_tokens(word, text)
news28.t <- news28.t %>% anti_join(stop_words)

news29 <- data_frame(text = news29)
news29.t <- news29 %>% unnest_tokens(word, text)
news29.t <- news29.t %>% anti_join(stop_words)

news30 <- data_frame(text = news30)
news30.t <- news30 %>% unnest_tokens(word, text)
news30.t <- news30.t %>% anti_join(stop_words)

sentiments # 3 sentiment lexicons avail in package tidytext

get_sentiments("nrc")
## positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise, and trust.

get_sentiments("afinn")
## Scoring from - 5 to +5 for each word

get_sentiments("bing")
## Neg or Pos for each word

# Most common words associated with Joy ------------------------------------------------------------------------
nrcjoy <- get_sentiments("nrc") %>% filter(sentiment == "joy")
news1.joy <- news1.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news2.joy <- news2.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news3.joy <- news3.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news4.joy <- news4.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news5.joy <- news5.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news6.joy <- news6.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news7.joy <- news7.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news8.joy <- news8.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news9.joy <- news9.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news10.joy <- news10.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news11.joy <- news11.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news12.joy <- news12.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news13.joy <- news13.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news14.joy <- news14.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news15.joy <- news15.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news16.joy <- news16.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news17.joy <- news17.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news18.joy <- news18.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news19.joy <- news19.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news20.joy <- news20.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news21.joy <- news21.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news22.joy <- news22.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news23.joy <- news23.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news24.joy <- news24.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news25.joy <- news25.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news26.joy <- news26.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news27.joy <- news27.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news28.joy <- news28.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news29.joy <- news29.t %>% inner_join(nrcjoy) %>% count(word, sort = T)
news30.joy <- news30.t %>% inner_join(nrcjoy) %>% count(word, sort = T)

nrctrust <- get_sentiments("nrc") %>% filter(sentiment == "trust")
news1.trust <- news1.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news2.trust <- news2.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news3.trust <- news3.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news4.trust <- news4.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news5.trust <- news5.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news6.trust <- news6.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news7.trust <- news7.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news8.trust <- news8.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news9.trust <- news9.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news10.trust <- news10.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news11.trust <- news11.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news12.trust <- news12.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news13.trust <- news13.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news14.trust <- news14.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news15.trust <- news15.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news16.trust <- news16.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news17.trust <- news17.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news18.trust <- news18.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news19.trust <- news19.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news20.trust <- news20.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news21.trust <- news21.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news22.trust <- news22.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news23.trust <- news23.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news24.trust <- news24.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news25.trust <- news25.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news26.trust <- news26.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news27.trust <- news27.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news28.trust <- news28.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news29.trust <- news29.t %>% inner_join(nrctrust) %>% count(word, sort = T)
news30.trust <- news30.t %>% inner_join(nrctrust) %>% count(word, sort = T)

nrcfear <- get_sentiments("nrc") %>% filter(sentiment == "fear")
news1.fear <- news1.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news2.fear <- news2.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news3.fear <- news3.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news4.fear <- news4.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news5.fear <- news5.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news6.fear <- news6.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news7.fear <- news7.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news8.fear <- news8.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news9.fear <- news9.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news10.fear <- news10.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news11.fear <- news11.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news12.fear <- news12.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news13.fear <- news13.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news14.fear <- news14.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news15.fear <- news15.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news16.fear <- news16.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news17.fear <- news17.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news18.fear <- news18.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news19.fear <- news19.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news20.fear <- news20.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news21.fear <- news21.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news22.fear <- news22.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news23.fear <- news23.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news24.fear <- news24.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news25.fear <- news25.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news26.fear <- news26.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news27.fear <- news27.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news28.fear <- news28.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news29.fear <- news29.t %>% inner_join(nrcfear) %>% count(word, sort = T)
news30.fear <- news30.t %>% inner_join(nrcfear) %>% count(word, sort = T)

nrcnegative <- get_sentiments("nrc") %>% filter(sentiment == "negative")
news1.negative <- news1.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news2.negative <- news2.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news3.negative <- news3.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news4.negative <- news4.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news5.negative <- news5.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news6.negative <- news6.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news7.negative <- news7.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news8.negative <- news8.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news9.negative <- news9.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news10.negative <- news10.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news11.negative <- news11.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news12.negative <- news12.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news13.negative <- news13.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news14.negative <- news14.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news15.negative <- news15.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news16.negative <- news16.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news17.negative <- news17.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news18.negative <- news18.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news19.negative <- news19.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news20.negative <- news20.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news21.negative <- news21.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news22.negative <- news22.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news23.negative <- news23.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news24.negative <- news24.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news25.negative <- news25.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news26.negative <- news26.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news27.negative <- news27.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news28.negative <- news28.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news29.negative <- news29.t %>% inner_join(nrcnegative) %>% count(word, sort = T)
news30.negative <- news30.t %>% inner_join(nrcnegative) %>% count(word, sort = T)

nrcsadness <- get_sentiments("nrc") %>% filter(sentiment == "sadness")
news1.sadness <- news1.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news2.sadness <- news2.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news3.sadness <- news3.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news4.sadness <- news4.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news5.sadness <- news5.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news6.sadness <- news6.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news7.sadness <- news7.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news8.sadness <- news8.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news9.sadness <- news9.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news10.sadness <- news10.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news11.sadness <- news11.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news12.sadness <- news12.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news13.sadness <- news13.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news14.sadness <- news14.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news15.sadness <- news15.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news16.sadness <- news16.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news17.sadness <- news17.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news18.sadness <- news18.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news19.sadness <- news19.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news20.sadness <- news20.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news21.sadness <- news21.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news22.sadness <- news22.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news23.sadness <- news23.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news24.sadness <- news24.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news25.sadness <- news25.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news26.sadness <- news26.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news27.sadness <- news27.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news28.sadness <- news28.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news29.sadness <- news29.t %>% inner_join(nrcsadness) %>% count(word, sort = T)
news30.sadness <- news30.t %>% inner_join(nrcsadness) %>% count(word, sort = T)

nrcanger <- get_sentiments("nrc") %>% filter(sentiment == "anger")
news1.anger <- news1.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news2.anger <- news2.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news3.anger <- news3.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news4.anger <- news4.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news5.anger <- news5.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news6.anger <- news6.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news7.anger <- news7.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news8.anger <- news8.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news9.anger <- news9.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news10.anger <- news10.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news11.anger <- news11.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news12.anger <- news12.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news13.anger <- news13.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news14.anger <- news14.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news15.anger <- news15.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news16.anger <- news16.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news17.anger <- news17.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news18.anger <- news18.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news19.anger <- news19.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news20.anger <- news20.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news21.anger <- news21.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news22.anger <- news22.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news23.anger <- news23.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news24.anger <- news24.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news25.anger <- news25.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news26.anger <- news26.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news27.anger <- news27.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news28.anger <- news28.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news29.anger <- news29.t %>% inner_join(nrcanger) %>% count(word, sort = T)
news30.anger <- news30.t %>% inner_join(nrcanger) %>% count(word, sort = T)

nrcsurprise <- get_sentiments("nrc") %>% filter(sentiment == "surprise")
news1.surprise <- news1.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news2.surprise <- news2.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news3.surprise <- news3.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news4.surprise <- news4.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news5.surprise <- news5.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news6.surprise <- news6.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news7.surprise <- news7.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news8.surprise <- news8.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news9.surprise <- news9.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news10.surprise <- news10.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news11.surprise <- news11.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news12.surprise <- news12.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news13.surprise <- news13.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news14.surprise <- news14.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news15.surprise <- news15.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news16.surprise <- news16.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news17.surprise <- news17.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news18.surprise <- news18.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news19.surprise <- news19.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news20.surprise <- news20.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news21.surprise <- news21.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news22.surprise <- news22.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news23.surprise <- news23.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news24.surprise <- news24.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news25.surprise <- news25.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news26.surprise <- news26.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news27.surprise <- news27.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news28.surprise <- news28.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news29.surprise <- news29.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)
news30.surprise <- news30.t %>% inner_join(nrcsurprise) %>% count(word, sort = T)

nrcpositive <- get_sentiments("nrc") %>% filter(sentiment == "positive")
news1.positive <- news1.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news2.positive <- news2.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news3.positive <- news3.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news4.positive <- news4.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news5.positive <- news5.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news6.positive <- news6.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news7.positive <- news7.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news8.positive <- news8.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news9.positive <- news9.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news10.positive <- news10.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news11.positive <- news11.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news12.positive <- news12.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news13.positive <- news13.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news14.positive <- news14.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news15.positive <- news15.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news16.positive <- news16.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news17.positive <- news17.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news18.positive <- news18.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news19.positive <- news19.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news20.positive <- news20.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news21.positive <- news21.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news22.positive <- news22.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news23.positive <- news23.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news24.positive <- news24.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news25.positive <- news25.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news26.positive <- news26.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news27.positive <- news27.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news28.positive <- news28.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news29.positive <- news29.t %>% inner_join(nrcpositive) %>% count(word, sort = T)
news30.positive <- news30.t %>% inner_join(nrcpositive) %>% count(word, sort = T)

nrcdisgust <- get_sentiments("nrc") %>% filter(sentiment == "disgust")
news1.disgust <- news1.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news2.disgust <- news2.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news3.disgust <- news3.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news4.disgust <- news4.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news5.disgust <- news5.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news6.disgust <- news6.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news7.disgust <- news7.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news8.disgust <- news8.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news9.disgust <- news9.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news10.disgust <- news10.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news11.disgust <- news11.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news12.disgust <- news12.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news13.disgust <- news13.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news14.disgust <- news14.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news15.disgust <- news15.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news16.disgust <- news16.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news17.disgust <- news17.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news18.disgust <- news18.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news19.disgust <- news19.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news20.disgust <- news20.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news21.disgust <- news21.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news22.disgust <- news22.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news23.disgust <- news23.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news24.disgust <- news24.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news25.disgust <- news25.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news26.disgust <- news26.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news27.disgust <- news27.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news28.disgust <- news28.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news29.disgust <- news29.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)
news30.disgust <- news30.t %>% inner_join(nrcdisgust) %>% count(word, sort = T)

nrcanticipation <- get_sentiments("nrc") %>% filter(sentiment == "anticipation")
news1.anticipation <- news1.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news2.anticipation <- news2.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news3.anticipation <- news3.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news4.anticipation <- news4.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news5.anticipation <- news5.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news6.anticipation <- news6.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news7.anticipation <- news7.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news8.anticipation <- news8.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news9.anticipation <- news9.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news10.anticipation <- news10.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news11.anticipation <- news11.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news12.anticipation <- news12.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news13.anticipation <- news13.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news14.anticipation <- news14.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news15.anticipation <- news15.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news16.anticipation <- news16.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news17.anticipation <- news17.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news18.anticipation <- news18.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news19.anticipation <- news19.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news20.anticipation <- news20.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news21.anticipation <- news21.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news22.anticipation <- news22.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news23.anticipation <- news23.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news24.anticipation <- news24.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news25.anticipation <- news25.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news26.anticipation <- news26.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news27.anticipation <- news27.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news28.anticipation <- news28.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news29.anticipation <- news29.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)
news30.anticipation <- news30.t %>% inner_join(nrcanticipation) %>% count(word, sort = T)

# Most common positive and negative words by Bing lexicon ------------------------------------------------------
# Spread() in package tidyr to list Neg and Pos sentiments in another columns
news1.sen <- news1.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news2.sen <- news2.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news3.sen <- news3.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news4.sen <- news4.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news5.sen <- news5.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news6.sen <- news6.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news7.sen <- news7.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news8.sen <- news8.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news9.sen <- news9.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news10.sen <- news10.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news11.sen <- news11.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news12.sen <- news12.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news13.sen <- news13.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news14.sen <- news14.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news15.sen <- news15.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news16.sen <- news16.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news17.sen <- news17.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news18.sen <- news18.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news19.sen <- news19.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news20.sen <- news20.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news21.sen <- news21.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news22.sen <- news22.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news23.sen <- news23.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news24.sen <- news24.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news25.sen <- news25.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news26.sen <- news26.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news27.sen <- news27.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news28.sen <- news28.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news29.sen <- news29.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))
news30.sen <- news30.t %>% inner_join(get_sentiments("bing")) %>% count(word, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% mutate(sentiment = positive - negative) %>% arrange(desc(sentiment))

# Sentiment by Afinn value -5 to 5 per word -----------------------------------------------------------------------
news1.sen.af <- news1.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news2.sen.af <- news2.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news3.sen.af <- news3.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news4.sen.af <- news4.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news5.sen.af <- news5.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news6.sen.af <- news6.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news7.sen.af <- news7.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news8.sen.af <- news8.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news9.sen.af <- news9.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news10.sen.af <- news10.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news11.sen.af <- news11.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news12.sen.af <- news12.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news13.sen.af <- news13.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news14.sen.af <- news14.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news15.sen.af <- news15.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news16.sen.af <- news16.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news17.sen.af <- news17.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news18.sen.af <- news18.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news19.sen.af <- news19.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news20.sen.af <- news20.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news21.sen.af <- news21.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news22.sen.af <- news22.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news23.sen.af <- news23.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news24.sen.af <- news24.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news25.sen.af <- news25.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news26.sen.af <- news26.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news27.sen.af <- news27.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news28.sen.af <- news28.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news29.sen.af <- news29.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))
news30.sen.af <- news30.t %>% inner_join(get_sentiments("afinn")) %>% count(word, value) %>% arrange(desc(value))


# Overall Sentiment Across the 3 Rallys ----------------------------------------------------------------------
overall <- data.frame(Sentiment.Bing = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Afinn = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Joy = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Trust = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Fear = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Negative = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Sadness = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Anger = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Surprise = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), Sentiment.Positive = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),Sentiment.Disgust = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),Sentiment.Anticipation = c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0), row.names = c("news1", "news2", "news3", "news4", "news5", "news6", "news7", "news8", "news9", "news10", "news11", "news12", "news13", "news14", "news15", "news16", "news17", "news18", "news19", "news20", "news21", "news22", "news23", "news24", "news25", "news26", "news27", "news28", "news29", "news30"))

overall$Sentiment.Bing[1] <- news1.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[2] <- news2.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[3] <- news3.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[4] <- news4.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[5] <- news5.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[6] <- news6.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[7] <- news7.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[8] <- news8.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[9] <- news9.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[10] <- news10.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[11] <- news11.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[12] <- news12.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[13] <- news13.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[14] <- news14.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[15] <- news15.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[16] <- news16.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[17] <- news17.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[18] <- news18.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[19] <- news19.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[20] <- news20.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[21] <- news21.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[22] <- news22.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[23] <- news23.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[24] <- news24.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[25] <- news25.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[26] <- news26.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[27] <- news27.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[28] <- news28.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[29] <- news29.sen %>% summarise(sum(sentiment))
overall$Sentiment.Bing[30] <- news30.sen %>% summarise(sum(sentiment))

overall$Sentiment.Afinn[1] <- news1.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[2] <- news2.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[3] <- news3.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[4] <- news4.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[5] <- news5.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[6] <- news6.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[7] <- news7.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[8] <- news8.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[9] <- news9.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[10] <- news10.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[11] <- news11.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[12] <- news12.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[13] <- news13.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[14] <- news14.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[15] <- news15.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[16] <- news16.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[17] <- news17.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[18] <- news18.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[19] <- news19.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[20] <- news20.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[21] <- news21.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[22] <- news22.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[23] <- news23.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[24] <- news24.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[25] <- news25.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[26] <- news26.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[27] <- news27.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[28] <- news28.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[29] <- news29.sen.af %>% summarise(sum(value*n))
overall$Sentiment.Afinn[30] <- news30.sen.af %>% summarise(sum(value*n))

overall$Sentiment.Joy[1] <- news1.joy %>% summarise(sum(n))
overall$Sentiment.Joy[2] <- news2.joy %>% summarise(sum(n))
overall$Sentiment.Joy[3] <- news3.joy %>% summarise(sum(n))
overall$Sentiment.Joy[4] <- news4.joy %>% summarise(sum(n))
overall$Sentiment.Joy[5] <- news5.joy %>% summarise(sum(n))
overall$Sentiment.Joy[6] <- news6.joy %>% summarise(sum(n))
overall$Sentiment.Joy[7] <- news7.joy %>% summarise(sum(n))
overall$Sentiment.Joy[8] <- news8.joy %>% summarise(sum(n))
overall$Sentiment.Joy[9] <- news9.joy %>% summarise(sum(n))
overall$Sentiment.Joy[10] <- news10.joy %>% summarise(sum(n))
overall$Sentiment.Joy[11] <- news11.joy %>% summarise(sum(n))
overall$Sentiment.Joy[12] <- news12.joy %>% summarise(sum(n))
overall$Sentiment.Joy[13] <- news13.joy %>% summarise(sum(n))
overall$Sentiment.Joy[14] <- news14.joy %>% summarise(sum(n))
overall$Sentiment.Joy[15] <- news15.joy %>% summarise(sum(n))
overall$Sentiment.Joy[16] <- news16.joy %>% summarise(sum(n))
overall$Sentiment.Joy[17] <- news17.joy %>% summarise(sum(n))
overall$Sentiment.Joy[18] <- news18.joy %>% summarise(sum(n))
overall$Sentiment.Joy[19] <- news19.joy %>% summarise(sum(n))
overall$Sentiment.Joy[20] <- news20.joy %>% summarise(sum(n))
overall$Sentiment.Joy[21] <- news21.joy %>% summarise(sum(n))
overall$Sentiment.Joy[22] <- news22.joy %>% summarise(sum(n))
overall$Sentiment.Joy[23] <- news23.joy %>% summarise(sum(n))
overall$Sentiment.Joy[24] <- news24.joy %>% summarise(sum(n))
overall$Sentiment.Joy[25] <- news25.joy %>% summarise(sum(n))
overall$Sentiment.Joy[26] <- news26.joy %>% summarise(sum(n))
overall$Sentiment.Joy[27] <- news27.joy %>% summarise(sum(n))
overall$Sentiment.Joy[28] <- news28.joy %>% summarise(sum(n))
overall$Sentiment.Joy[29] <- news29.joy %>% summarise(sum(n))
overall$Sentiment.Joy[30] <- news30.joy %>% summarise(sum(n))

overall$Sentiment.Trust[1] <- news1.trust %>% summarise(sum(n))
overall$Sentiment.Trust[2] <- news2.trust %>% summarise(sum(n))
overall$Sentiment.Trust[3] <- news3.trust %>% summarise(sum(n))
overall$Sentiment.Trust[4] <- news4.trust %>% summarise(sum(n))
overall$Sentiment.Trust[5] <- news5.trust %>% summarise(sum(n))
overall$Sentiment.Trust[6] <- news6.trust %>% summarise(sum(n))
overall$Sentiment.Trust[7] <- news7.trust %>% summarise(sum(n))
overall$Sentiment.Trust[8] <- news8.trust %>% summarise(sum(n))
overall$Sentiment.Trust[9] <- news9.trust %>% summarise(sum(n))
overall$Sentiment.Trust[10] <- news10.trust %>% summarise(sum(n))
overall$Sentiment.Trust[11] <- news11.trust %>% summarise(sum(n))
overall$Sentiment.Trust[12] <- news12.trust %>% summarise(sum(n))
overall$Sentiment.Trust[13] <- news13.trust %>% summarise(sum(n))
overall$Sentiment.Trust[14] <- news14.trust %>% summarise(sum(n))
overall$Sentiment.Trust[15] <- news15.trust %>% summarise(sum(n))
overall$Sentiment.Trust[16] <- news16.trust %>% summarise(sum(n))
overall$Sentiment.Trust[17] <- news17.trust %>% summarise(sum(n))
overall$Sentiment.Trust[18] <- news18.trust %>% summarise(sum(n))
overall$Sentiment.Trust[19] <- news19.trust %>% summarise(sum(n))
overall$Sentiment.Trust[20] <- news20.trust %>% summarise(sum(n))
overall$Sentiment.Trust[21] <- news21.trust %>% summarise(sum(n))
overall$Sentiment.Trust[22] <- news22.trust %>% summarise(sum(n))
overall$Sentiment.Trust[23] <- news23.trust %>% summarise(sum(n))
overall$Sentiment.Trust[24] <- news24.trust %>% summarise(sum(n))
overall$Sentiment.Trust[25] <- news25.trust %>% summarise(sum(n))
overall$Sentiment.Trust[26] <- news26.trust %>% summarise(sum(n))
overall$Sentiment.Trust[27] <- news27.trust %>% summarise(sum(n))
overall$Sentiment.Trust[28] <- news28.trust %>% summarise(sum(n))
overall$Sentiment.Trust[29] <- news29.trust %>% summarise(sum(n))
overall$Sentiment.Trust[30] <- news30.trust %>% summarise(sum(n))

overall$Sentiment.Fear[1] <- news1.fear %>% summarise(sum(n))
overall$Sentiment.Fear[2] <- news2.fear %>% summarise(sum(n))
overall$Sentiment.Fear[3] <- news3.fear %>% summarise(sum(n))
overall$Sentiment.Fear[4] <- news4.fear %>% summarise(sum(n))
overall$Sentiment.Fear[5] <- news5.fear %>% summarise(sum(n))
overall$Sentiment.Fear[6] <- news6.fear %>% summarise(sum(n))
overall$Sentiment.Fear[7] <- news7.fear %>% summarise(sum(n))
overall$Sentiment.Fear[8] <- news8.fear %>% summarise(sum(n))
overall$Sentiment.Fear[9] <- news9.fear %>% summarise(sum(n))
overall$Sentiment.Fear[10] <- news10.fear %>% summarise(sum(n))
overall$Sentiment.Fear[11] <- news11.fear %>% summarise(sum(n))
overall$Sentiment.Fear[12] <- news12.fear %>% summarise(sum(n))
overall$Sentiment.Fear[13] <- news13.fear %>% summarise(sum(n))
overall$Sentiment.Fear[14] <- news14.fear %>% summarise(sum(n))
overall$Sentiment.Fear[15] <- news15.fear %>% summarise(sum(n))
overall$Sentiment.Fear[16] <- news16.fear %>% summarise(sum(n))
overall$Sentiment.Fear[17] <- news17.fear %>% summarise(sum(n))
overall$Sentiment.Fear[18] <- news18.fear %>% summarise(sum(n))
overall$Sentiment.Fear[19] <- news19.fear %>% summarise(sum(n))
overall$Sentiment.Fear[20] <- news20.fear %>% summarise(sum(n))
overall$Sentiment.Fear[21] <- news21.fear %>% summarise(sum(n))
overall$Sentiment.Fear[22] <- news22.fear %>% summarise(sum(n))
overall$Sentiment.Fear[23] <- news23.fear %>% summarise(sum(n))
overall$Sentiment.Fear[24] <- news24.fear %>% summarise(sum(n))
overall$Sentiment.Fear[25] <- news25.fear %>% summarise(sum(n))
overall$Sentiment.Fear[26] <- news26.fear %>% summarise(sum(n))
overall$Sentiment.Fear[27] <- news27.fear %>% summarise(sum(n))
overall$Sentiment.Fear[28] <- news28.fear %>% summarise(sum(n))
overall$Sentiment.Fear[29] <- news29.fear %>% summarise(sum(n))
overall$Sentiment.Fear[30] <- news30.fear %>% summarise(sum(n))

overall$Sentiment.Negative[1] <- news1.negative %>% summarise(sum(n))
overall$Sentiment.Negative[2] <- news2.negative %>% summarise(sum(n))
overall$Sentiment.Negative[3] <- news3.negative %>% summarise(sum(n))
overall$Sentiment.Negative[4] <- news4.negative %>% summarise(sum(n))
overall$Sentiment.Negative[5] <- news5.negative %>% summarise(sum(n))
overall$Sentiment.Negative[6] <- news6.negative %>% summarise(sum(n))
overall$Sentiment.Negative[7] <- news7.negative %>% summarise(sum(n))
overall$Sentiment.Negative[8] <- news8.negative %>% summarise(sum(n))
overall$Sentiment.Negative[9] <- news9.negative %>% summarise(sum(n))
overall$Sentiment.Negative[10] <- news10.negative %>% summarise(sum(n))
overall$Sentiment.Negative[11] <- news11.negative %>% summarise(sum(n))
overall$Sentiment.Negative[12] <- news12.negative %>% summarise(sum(n))
overall$Sentiment.Negative[13] <- news13.negative %>% summarise(sum(n))
overall$Sentiment.Negative[14] <- news14.negative %>% summarise(sum(n))
overall$Sentiment.Negative[15] <- news15.negative %>% summarise(sum(n))
overall$Sentiment.Negative[16] <- news16.negative %>% summarise(sum(n))
overall$Sentiment.Negative[17] <- news17.negative %>% summarise(sum(n))
overall$Sentiment.Negative[18] <- news18.negative %>% summarise(sum(n))
overall$Sentiment.Negative[19] <- news19.negative %>% summarise(sum(n))
overall$Sentiment.Negative[20] <- news20.negative %>% summarise(sum(n))
overall$Sentiment.Negative[21] <- news21.negative %>% summarise(sum(n))
overall$Sentiment.Negative[22] <- news22.negative %>% summarise(sum(n))
overall$Sentiment.Negative[23] <- news23.negative %>% summarise(sum(n))
overall$Sentiment.Negative[24] <- news24.negative %>% summarise(sum(n))
overall$Sentiment.Negative[25] <- news25.negative %>% summarise(sum(n))
overall$Sentiment.Negative[26] <- news26.negative %>% summarise(sum(n))
overall$Sentiment.Negative[27] <- news27.negative %>% summarise(sum(n))
overall$Sentiment.Negative[28] <- news28.negative %>% summarise(sum(n))
overall$Sentiment.Negative[29] <- news29.negative %>% summarise(sum(n))
overall$Sentiment.Negative[30] <- news30.negative %>% summarise(sum(n))

overall$Sentiment.Sadness[1] <- news1.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[2] <- news2.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[3] <- news3.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[4] <- news4.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[5] <- news5.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[6] <- news6.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[7] <- news7.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[8] <- news8.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[9] <- news9.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[10] <- news10.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[11] <- news11.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[12] <- news12.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[13] <- news13.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[14] <- news14.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[15] <- news15.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[16] <- news16.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[17] <- news17.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[18] <- news18.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[19] <- news19.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[20] <- news20.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[21] <- news21.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[22] <- news22.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[23] <- news23.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[24] <- news24.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[25] <- news25.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[26] <- news26.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[27] <- news27.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[28] <- news28.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[29] <- news29.sadness %>% summarise(sum(n))
overall$Sentiment.Sadness[30] <- news30.sadness %>% summarise(sum(n))

overall$Sentiment.Anger[1] <- news1.anger %>% summarise(sum(n))
overall$Sentiment.Anger[2] <- news2.anger %>% summarise(sum(n))
overall$Sentiment.Anger[3] <- news3.anger %>% summarise(sum(n))
overall$Sentiment.Anger[4] <- news4.anger %>% summarise(sum(n))
overall$Sentiment.Anger[5] <- news5.anger %>% summarise(sum(n))
overall$Sentiment.Anger[6] <- news6.anger %>% summarise(sum(n))
overall$Sentiment.Anger[7] <- news7.anger %>% summarise(sum(n))
overall$Sentiment.Anger[8] <- news8.anger %>% summarise(sum(n))
overall$Sentiment.Anger[9] <- news9.anger %>% summarise(sum(n))
overall$Sentiment.Anger[10] <- news10.anger %>% summarise(sum(n))
overall$Sentiment.Anger[11] <- news11.anger %>% summarise(sum(n))
overall$Sentiment.Anger[12] <- news12.anger %>% summarise(sum(n))
overall$Sentiment.Anger[13] <- news13.anger %>% summarise(sum(n))
overall$Sentiment.Anger[14] <- news14.anger %>% summarise(sum(n))
overall$Sentiment.Anger[15] <- news15.anger %>% summarise(sum(n))
overall$Sentiment.Anger[16] <- news16.anger %>% summarise(sum(n))
overall$Sentiment.Anger[17] <- news17.anger %>% summarise(sum(n))
overall$Sentiment.Anger[18] <- news18.anger %>% summarise(sum(n))
overall$Sentiment.Anger[19] <- news19.anger %>% summarise(sum(n))
overall$Sentiment.Anger[20] <- news20.anger %>% summarise(sum(n))
overall$Sentiment.Anger[21] <- news21.anger %>% summarise(sum(n))
overall$Sentiment.Anger[22] <- news22.anger %>% summarise(sum(n))
overall$Sentiment.Anger[23] <- news23.anger %>% summarise(sum(n))
overall$Sentiment.Anger[24] <- news24.anger %>% summarise(sum(n))
overall$Sentiment.Anger[25] <- news25.anger %>% summarise(sum(n))
overall$Sentiment.Anger[26] <- news26.anger %>% summarise(sum(n))
overall$Sentiment.Anger[27] <- news27.anger %>% summarise(sum(n))
overall$Sentiment.Anger[28] <- news28.anger %>% summarise(sum(n))
overall$Sentiment.Anger[29] <- news29.anger %>% summarise(sum(n))
overall$Sentiment.Anger[30] <- news30.anger %>% summarise(sum(n))

overall$Sentiment.Surprise[1] <- news1.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[2] <- news2.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[3] <- news3.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[4] <- news4.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[5] <- news5.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[6] <- news6.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[7] <- news7.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[8] <- news8.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[9] <- news9.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[10] <- news10.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[11] <- news11.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[12] <- news12.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[13] <- news13.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[14] <- news14.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[15] <- news15.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[16] <- news16.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[17] <- news17.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[18] <- news18.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[19] <- news19.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[20] <- news20.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[21] <- news21.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[22] <- news22.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[23] <- news23.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[24] <- news24.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[25] <- news25.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[26] <- news26.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[27] <- news27.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[28] <- news28.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[29] <- news29.surprise %>% summarise(sum(n))
overall$Sentiment.Surprise[30] <- news30.surprise %>% summarise(sum(n))

overall$Sentiment.Positive[1] <- news1.positive %>% summarise(sum(n))
overall$Sentiment.Positive[2] <- news2.positive %>% summarise(sum(n))
overall$Sentiment.Positive[3] <- news3.positive %>% summarise(sum(n))
overall$Sentiment.Positive[4] <- news4.positive %>% summarise(sum(n))
overall$Sentiment.Positive[5] <- news5.positive %>% summarise(sum(n))
overall$Sentiment.Positive[6] <- news6.positive %>% summarise(sum(n))
overall$Sentiment.Positive[7] <- news7.positive %>% summarise(sum(n))
overall$Sentiment.Positive[8] <- news8.positive %>% summarise(sum(n))
overall$Sentiment.Positive[9] <- news9.positive %>% summarise(sum(n))
overall$Sentiment.Positive[10] <- news10.positive %>% summarise(sum(n))
overall$Sentiment.Positive[11] <- news11.positive %>% summarise(sum(n))
overall$Sentiment.Positive[12] <- news12.positive %>% summarise(sum(n))
overall$Sentiment.Positive[13] <- news13.positive %>% summarise(sum(n))
overall$Sentiment.Positive[14] <- news14.positive %>% summarise(sum(n))
overall$Sentiment.Positive[15] <- news15.positive %>% summarise(sum(n))
overall$Sentiment.Positive[16] <- news16.positive %>% summarise(sum(n))
overall$Sentiment.Positive[17] <- news17.positive %>% summarise(sum(n))
overall$Sentiment.Positive[18] <- news18.positive %>% summarise(sum(n))
overall$Sentiment.Positive[19] <- news19.positive %>% summarise(sum(n))
overall$Sentiment.Positive[20] <- news20.positive %>% summarise(sum(n))
overall$Sentiment.Positive[21] <- news21.positive %>% summarise(sum(n))
overall$Sentiment.Positive[22] <- news22.positive %>% summarise(sum(n))
overall$Sentiment.Positive[23] <- news23.positive %>% summarise(sum(n))
overall$Sentiment.Positive[24] <- news24.positive %>% summarise(sum(n))
overall$Sentiment.Positive[25] <- news25.positive %>% summarise(sum(n))
overall$Sentiment.Positive[26] <- news26.positive %>% summarise(sum(n))
overall$Sentiment.Positive[27] <- news27.positive %>% summarise(sum(n))
overall$Sentiment.Positive[28] <- news28.positive %>% summarise(sum(n))
overall$Sentiment.Positive[29] <- news29.positive %>% summarise(sum(n))
overall$Sentiment.Positive[30] <- news30.positive %>% summarise(sum(n))

overall$Sentiment.Disgust[1] <- news1.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[2] <- news2.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[3] <- news3.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[4] <- news4.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[5] <- news5.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[6] <- news6.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[7] <- news7.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[8] <- news8.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[9] <- news9.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[10] <- news10.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[11] <- news11.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[12] <- news12.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[13] <- news13.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[14] <- news14.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[15] <- news15.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[16] <- news16.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[17] <- news17.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[18] <- news18.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[19] <- news19.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[20] <- news20.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[21] <- news21.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[22] <- news22.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[23] <- news23.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[24] <- news24.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[25] <- news25.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[26] <- news26.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[27] <- news27.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[28] <- news28.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[29] <- news29.disgust %>% summarise(sum(n))
overall$Sentiment.Disgust[30] <- news30.disgust %>% summarise(sum(n))

overall$Sentiment.Anticipation[1] <- news1.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[2] <- news2.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[3] <- news3.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[4] <- news4.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[5] <- news5.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[6] <- news6.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[7] <- news7.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[8] <- news8.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[9] <- news9.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[10] <- news10.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[11] <- news11.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[12] <- news12.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[13] <- news13.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[14] <- news14.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[15] <- news15.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[16] <- news16.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[17] <- news17.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[18] <- news18.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[19] <- news19.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[20] <- news20.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[21] <- news21.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[22] <- news22.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[23] <- news23.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[24] <- news24.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[25] <- news25.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[26] <- news26.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[27] <- news27.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[28] <- news28.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[29] <- news29.anticipation %>% summarise(sum(n))
overall$Sentiment.Anticipation[30] <- news30.anticipation %>% summarise(sum(n))

overall

###############################################################################################
###############################################################################################
###############################################################################################

library(data.table)

data <- fread('Text Analytics STI.csv')
data1 <- data[, .(Price, Sentiment.Bing, Sentiment.Afinn, Sentiment.Joy, Sentiment.Trust, Sentiment.Fear, Sentiment.Negative, Sentiment.Sadness, Sentiment.Anger, Sentiment.Surprise, Sentiment.Positive, Sentiment.Disgust, Sentiment.Anticipation)]
str(data1)

# Linear Regression
m1 <- lm(Price ~ ., data=data1)
summary(m1)

# Decision Tree

library(data.table)
library(rpart)
library(rpart.plot)	# for enhanced tree plots

set.seed(2020)		# for randomisation in 10-fold CV
options(digits = 5)	# reduce the no. of decimals 
options(scipen = 999)	# remove all e notation
m2 <- rpart(Price ~ ., data = data1, method = 'anova', control = rpart.control(minsplit = 2, cp = 0)) 
# use method = 'anova' if continuous Y
# by default, cp = 0.01
rpart.plot(m2, nn = T, main = 'Chart Name') # tree plotting

CVerror.cap <- m2$cptable[which.min(m2$cptable[,'xerror']), 'xerror'] + m2$cptable[which.min(m2$cptable[,'xerror']), 'xstd'] # min CV + 1 SE
i <- 1; j <- 4		
while (m2$cptable[i,j] > CVerror.cap) {
  i <- i + 1
}
cp.opt = ifelse(i > 1, sqrt(m2$cptable[i,1] * m2$cptable[i-1, 1]), 1)

m2.1 <- prune(m2, cp = cp.opt)
print(m2.1)
m2.1$variable.importance


##############################################################################################
##############################################################################################
##############################################################################################

